feat(jobboard): add job section to homepage - fixes #66
ng-be/2016-www-ng-be-org pull request #70
Opened 2016-11-09 20:49 UTC by SamVerschueren

First draft of the job section. If you want some things differently, let me know. Also not sure about the grid classes I used. Not very familiair with them to be honest. So any help or improvements on those are more then welcome as well.

I hope this is what you where looking for. Feel free to say so if not, you don't have to merge because of my beautiful eyes. I can handle rejection ;).

2016-11-09 21:26 UTC, samvloeberghs requested changes

2016-11-09 21:26 UTC, samvloeberghs commented on src/components/jobboard/_build/jobboard.less
> +.community-logo {
Bad naming? Any specific reason why community?

2016-11-09 21:27 UTC, samvloeberghs commented
Thx Sam! Will look into the design tomorrow!

2016-11-10 06:17 UTC, samvloeberghs commented
@SamVerschueren as you see I've updated some parts of the grid, to also cover the mobile view better (1colom): I think it just needs the update of the naming like mentioned before.. nice job, thanks alot for this! :)

2016-11-10 06:19 UTC, samvloeberghs commented
what we could still need to agree on is where to put it exactly on the website. For now I would put it on every page:
- [ ] put include on every website

2016-11-10 08:05 UTC, SamVerschueren commented on src/components/jobboard/_build/jobboard.less
> +.community-logo {
It was a copy paste from the [sponsorcommunity stylesheet](https://github.com/ng-be/www-ng-be-org/blob/master/src/components/sponsorscommunity/_build/sponsorscommunity.less#L38). I agree, fixed it.

2016-11-10 08:08 UTC, SamVerschueren commented
I want to add it on every page, but wouldn't it clutter every page? Maybe we could add a `JOBS` page and show that information again instead? I'm just worried that we will have too much side-content on one page which is not associated directly with the main content of the page.

2016-11-10 09:45 UTC, samvloeberghs commented
@SamVerschueren let's consider that a different task!

2016-11-10 09:47 UTC, samvloeberghs approved these changes

2016-11-10 09:47 UTC, merged