update conference planning
ng-be/2016-www-ng-be-org pull request #79
Opened 2016-11-23 21:26 UTC by SamVerschueren

Update the conference planning. Let me know if anything has to be adjusted like this one maybe https://github.com/ng-be/www-ng-be-org/issues/76#issuecomment-262630291.

We can also wait for merging this when we have information of Pascal's talk.

2016-11-23 21:26 UTC, SamVerschueren commented on src/components/conference-day/conference-day.jade
> +                                p Keynote
Something else than just `Keynote`?

2016-11-23 21:27 UTC, SamVerschueren commented on src/components/conference-day/conference-day.jade
> +                                p The conference opening ceremony
Or just `Opening ceremony`?

2016-11-23 21:27 UTC, SamVerschueren commented on src/components/sponsors/sponsors.jade
> +        .container#ordina
Added these so we could link to them from the conference planning.

2016-11-24 08:56 UTC, samvloeberghs requested changes
Can you make the changes as request in the issue? thanks for your effort @SamVerschueren !!

2016-11-24 11:31 UTC, SamVerschueren commented
🎉  Not sure about the styling though. Care to check it out first?

2016-11-24 15:05 UTC, jvandemo commented
Thank you @SamVerschueren; much appreciated! 👍 

Meanwhile, Pascal's and Oliver's talk details are available:

Talk title
Angular and React: friends learning from each other

Talk description
React and Angular share a lot of architectural decisions and have inspired each other as well. They are both component oriented, have automated changed detection and can render both on the server as well as on the client side. However, there are also quite a few differences in how they work and which philosophy they follow. 

Based on advanced practical examples we will look at the most interesting differences between those two frameworks. This can help you understand your Angular framework even better and gives you insights into what strengths and what weaknesses it has in certain scenarios.

2016-11-24 15:12 UTC, jvandemo commented
Oliver, who will talk together with Pascal, has also sent us his details:

Oliver Zeigermann

Titel: Freelance Web Developer

Bio: Oliver Zeigermann is a developer and architect from Hamburg, Germany. Oliver is the co-author of the best selling German book on React, Redux, React Router, and Universal Rendering. He has also worked in several Angular and React projects using Flow and TypeScript. 

Twitter: @DJCordhose

2016-11-24 15:16 UTC, SamVerschueren commented
Ah sweet, thanks @jvandemo. Yesterday @samvloeberghs already added Oliver https://ng-be.org/conference-day#oliver-zeigermann.

Will update the talk description!

2016-11-24 15:20 UTC, SamVerschueren commented
Done. Only have to wait until the planning is finalised.

2016-11-24 16:18 UTC, jvandemo commented
Awesome, thank you @SamVerschueren! Feel free to ping me if you need anything from me. 👍

2016-11-28 19:17 UTC, samvloeberghs commented
Todd motto's description:

`In this talk we’ll take a deeper dive into Angular 2 Reactive forms and utilise the powerful APIs Angular 2 offers for complex forms, validation and much more.`

2016-11-28 19:31 UTC, SamVerschueren commented
Made the final changes. Also added Todd's description.

2016-11-28 19:32 UTC, SamVerschueren commented on src/_build/schedule.less
> +}
Maybe this could be done differently?

2016-11-28 22:02 UTC, samvloeberghs commented on src/_build/schedule.less
> +}
na that's perfect!

2016-11-28 22:03 UTC, samvloeberghs approved these changes

2016-11-28 22:03 UTC, merged

2016-11-29 08:26 UTC, SamVerschueren commented
Sweet! Thanks for merging!